- hosts: localhost
  tasks:
    - include_vars: vars.yml

    - name: Add sublime text PPA
      apt_repository:
        repo: '{{sublime_text_ppa}}'
        update_cache: yes
      become: yes

    - name: install with apt
      apt:
        name: '{{item}}'
        state: installed
      with_items: '{{apt}}'
      become: yes

    - name: install with npm
      npm: 
        name: '{{item}}' 
        global: yes
      with_items: '{{npm}}'
      become: yes

    - name: install nodejs using n
      command: bash -c 'n stable'
      become: yes

    - name: install oh my zsh
      command: bash -c 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"; chsh -s $(which zsh)'
      become: yes 

    - name: make zsh config 
      copy: src=~/.dotfiles/.zshrc dest=~/ mode=0777
      become: yes

    - name: make default oh my zsh
      command: bash -c 'chsh -s $(which zsh)'
      become: yes
    
    - name: vim config
      file: src=~/.dotfiles/.vimrc dest=~/.vimrc state=link force=true

    - name: Install PackageControl for Sublime
      get_url:
        url: https://packagecontrol.io/Package%20Control.sublime-package
        dest: ~/.config/sublime-text-3/Installed Packages/Package Control.sublime-package
