- hosts: localhost
  tasks:
    - include_vars: vars.yml

    - name: Add PPA
      apt_repository:
        repo: '{{item}}'
        update_cache: yes
      with_items: '{{ppa}}'  
      become: yes
    - name: yarn
      command: bash -c 'sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3 && echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list'

    - name: install with apt
      apt:
        name: '{{item}}'
        state: installed
      with_items: '{{apt}}'
      become: yes

    - name: install with npm
      npm: 
        name: '{{item}}' 
        global: yes
      with_items: '{{npm}}'
      become: yes

    - name: install nodejs using n
      command: bash -c 'n stable'
      become: yes

    - name: install oh my zsh
      command: bash -c 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"; chsh -s $(which zsh)'
      become: yes 

    - name: make default oh my zsh
      command: bash -c 'chsh -s $(which zsh)'
      become: yes
    
    - name: setup config files
      file: src=~/.dotfiles/{{item}} dest=~/{{item}} state=link force=true  
      with_items: '{{configs}}'

    - name: Install PackageControl for Sublime
      get_url:
        url: https://packagecontrol.io/Package%20Control.sublime-package
        dest: ~/.config/sublime-text-3/Installed Packages/Package Control.sublime-package

    - name: Install Hub
      git: repo=https://github.com/github/hub.git dest=~/hub/

    - name: Buid Hub
      command: bash -c 'cd ~/hub/ && ./script/build -o ~/bin/hub'
      become: yes 
    